model:
  INPUT_DIM: 20
  OUTPUT_DIM: 51
  HID_DIM: 512
  N_LAYERS: 2
  ENC_DROPOUT: 0.5
  DEC_DROPOUT: 0.5
training:
  N_EPOCHS: 10
  CLIP: 1
  THRESHOLD: 0.01
data-split:
  BATCH_SIZE: 5
  SEQ_LEN: 720
  TRAIN_RATIO: 0.7
  VALID_RATIO: 0.2
  TEST_RATIO: 0.1
